defaults:
  - scope:
      path: ""
      type: jobs
    values:
      layout: job

collections:
  jobs:
    output: true

excerpt_separator: <!--more-->

title: "cg.jobs"
author: cg

plugins:
  - jekyll-redirect-from

sass:
  style: compact
